spring.application.name=app

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jackdsql_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}
spring.datasource.driver-class-name=org.postgresql.Driver
sandbox.datasource.username=${SANDBOX_DATASOURCE_USERNAME:jackdsql_reader}
sandbox.datasource.password=${SANDBOX_DATASOURCE_PASSWORD:readonly_password123}

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=86400000

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

jackdsql.security.master-secret=${JACKDSQL_MASTER_SECRET}
jackdsql.security.master-salt=${JACKDSQL_MASTER_SALT}

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL_ENABLED:false}

# RabbitMQ Configuration
spring.rabbitmq.addresses=${SPRING_RABBITMQ_ADDRESSES:amqp://guest:guest@localhost:5672}